
GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62581919dda276c37cc7e51a

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amzing Person 2",
    "subscribedToChannel": "Web Dev Simplified 2"
}

